Доступная разметка главной страницы
htmlacademy-htmlcss/1588037-sedona-29 pull request #15
Opened 2020-10-11 18:21 UTC by Viktoria-W

2020-10-11 18:41 UTC, DoberBober requested changes
1. Кнопка "Поиск гостиницы в Седоне" - ссылка (href тоже пропиши какой-нибудь).
2. Кнопкам с календарём, плюсом и минусом в модалке добавь aria-label или скрытый текст с visually-hidden.
3. Логотипу академии на футере тоже.
4. В соцсетях текст с visually-hidden вставь внутрь ссылок.
5. У .container-map убери z-index -1. Вместо этого футеру добавь, чтобы сверху был. Под iframe вставь картинку с картой (сам iframe абсолютом над картинкой будет получается). Title и aria-hidden у карты удали, это лишнее.

2020-10-11 20:19 UTC, Viktoria-W commented
Не смотри тогда пока на страницу гостиниц, я на главной все исправила как ты сказал, а ту переделаю и открою новый пулреквест, сори что поторопилась.)

2020-10-12 15:28 UTC, DoberBober commented on index.html
> +                <a href="#" type="button" id="search" class="search-button"><p>Поиск гостиницы в седоне</p></a>
1. type удали (это ж ссылка).
2. href какой-нибудь пропиши (например, `href="search.html`), это будет проверяться.
3. `p` лишняя, от неё спокойно можно избавиться.

2020-10-12 15:29 UTC, DoberBober approved these changes
Из-за мелочи не буду отклонять. На своей стороне поправь, со следующим заданием скинешь.

2020-10-12 15:29 UTC, merged