Стилизация внутренней страницы
htmlacademy-htmlcss/1588037-sedona-29 pull request #5
Opened 2020-09-16 20:24 UTC by Viktoria-W

2020-09-16 20:32 UTC, DoberBober commented on hotels.html
> +              <ul class="search-result-category">
Не заметил в прошлый раз. Пункт "сортировка" вытащи, пожалуйста, из списка. Это больше как заголовок/описание/название идёт и не является равнозначным пунктам "по типу", "по цене". Поэтому неправильно их ставить в общий список. Сделай тегом `b/p/ещё_что-нибудь`.

2020-09-16 20:36 UTC, DoberBober commented on css/style.css
> +.hotels h3:hover {
Делать просто ховеры/активы на неинтерактивные элементы смысла нет.
Но в стайлгайде есть нарисованные состояния. Стало быть, подразумевается, что названия гостиниц будут ссылками. Дополни разметку (попробуй вариант с ссылкой внутри заголовка и наоборот. Посмотрим, заметишь ли в чём разница) и оформи наведение/нажатие уже самой ссылки.

2020-09-16 20:37 UTC, DoberBober requested changes
.

2020-09-16 21:48 UTC, Viktoria-W commented on css/style.css
> +.hotels h3:hover {
если поставить <a> перед  <h3>, то проигнорируются заданные размеры, а размер станет как для <h3> в em, а если наоборот, то заданые мной размеры сохранятся, правильно?

2020-09-16 21:50 UTC, Viktoria-W commented
Правильно поняла что если поставить ссылку перед заголовком, то заголовок проигнорирует заданные ему параметры в CSS, а если наоборот, то он станет заданного в font-sizе размера?)

2020-09-17 10:27 UTC, DoberBober commented on css/style.css
> +.hotels a {
Это, кажется, что-то лишнее. Переопределяет стили у `reserve` и `more`. Из-за такой мелочи возвращать не буду. У себя просто посмотри и поправь, если требуется.

2020-09-17 10:32 UTC, DoberBober approved these changes
> Правильно поняла что если поставить ссылку перед заголовком, то заголовок проигнорирует заданные ему параметры в CSS, а если наоборот, то он станет заданного в font-size размера?)

Я не совсем про это. Тут проблема в наследуемости просто.
Я про другое. Если ты поставишь заголовок внутри ссылки, то он будет эту ссылку растягивать под себя. В итоге область ссылки становится больше "ожидаемой". Это небольшая мелочь, которая просто влияет на ощущения, возникающие от сайта. Полезно знать.
![image](https://user-images.githubusercontent.com/18398812/93459107-e8801d00-f8e9-11ea-83ac-1de535fd95af.png)
![image](https://user-images.githubusercontent.com/18398812/93459185-0188ce00-f8ea-11ea-8d3c-9ae3e4a38e90.png)

2020-09-17 10:33 UTC, merged